contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"
starticdir = "static"
baseurl = "http://github.com/YadavRavi/YadavRavi.github.io"
title = "Ravi Yadav's Blog"
canonifyurls = true
paginate = 10
theme = "/themes/startbootstrap-clean-blog/"
languageCode = "de-DE"
copyright = "© by Ravi Yadav 2015"
pygmentsstyle = "friendly"
metaDataFormat = "yaml"

[author]
  name = "Ravi Yadav"

[params]
  DateForm = "Mon, Nov 30, 2015"
  Description = "Private Blog of Ravi Yadav"
  Author = "Ravi Yadav"
  email = "ravi.yadav@posteo.de"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/ravi_yadav_de"
[[params.social]]
  title = "github"
  url = "https://github.com/YadavRavi/YadavRavi.github.io"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/ravi.yadav2"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180