---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://github.com/YadavRavi/YadavRavi.github.io"
title: "Ravi Yadav's bloggings"
canonifyurls: true
copyright: "Ravi Yadav"
pygmentsstyle: "friendly"
author:
  name: "Ravi Yadav"
permalinks:
  blog: /:year/:month/:day/:slug/
blackfriday:
  angledQuotes: true
  fractions: false
  plainIdAnchors: true
  extensions:
    - hardLineBreak
params:
  ProfilePicture: "static/profile.jpg"
  enableLandingPage: true
  landingPageRedirectUrl: "/about/"
  AuthorName: "Ravi Yadav"
